### ISSUE TITLE
error when including react-style-webpack-plugin in webpack.config.js

### ISSUE THREAD

**Issue by jorda0mega** [js-next/react-style-webpack-plugin#12]
the moment I include this plugin as part of my webpack.config.js I get an error. Seems like it cannot some DOM elements?

Here is the webpack.config.js
``` javascript
var webpack = require('webpack');
var path = require('path');
var ReactStylePlugin = require('react-style-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: "source-map",
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    'bootstrap-webpack!bootstrap.config.js',
    './scripts/index'
  ],
  output: {
    path: __dirname + '/build/',
    filename: 'bundle.js',
    publicPath: '/build/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      "windows.jQuery": 'jquery'
    }),
    new ReactStylePlugin('bundle.css')
  ],
  resolve: {
    root: [path.resolve(__dirname), path.resolve(__dirname, "./styles")],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      { test: /\.css$/, loaders: ['style', 'css']},
      { test: /\.less?$/, loader: 'style!css!less'},
      { test: /\.jsx?$/, loaders: ['react-hot',ReactStylePlugin.loader(),'babel'], exclude: [/node_modules/, /\.config.jsx?$/] },
      { test: /\.woff$/,   loader: "url-loader?limit=10000&minetype=application/font-woff" },
      { test: /\.woff2$/,   loader: "url-loader?limit=10000&minetype=application/font-woff" },
      { test: /\.ttf$/,    loader: "file-loader" },
      { test: /\.eot$/,    loader: "file-loader" },
      { test: /\.svg$/,    loader: "file-loader" }
    ]
  }
};
```

Error:
```
ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!./~/bootstrap-webpack/index.loader.js!./bootstrap.config.js
Module build failed: ReferenceError: document is not defined
    at addStyle (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:5956:22)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:5937:3)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:468:30)
    at fn (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:40:20)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:501:2)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:468:30)
    at /Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:493:37
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/bootstrap-webpack/index.loader.js!/Users/jorgef/dev/cervojo/bootstrap.config.js:496:10)
    at Module._compile (module.js:460:26)
    at Object.loaderContext.exec (/Users/jorgef/dev/cervojo/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:86:7)

ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!./scripts/index.jsx
Module build failed: Error: Invariant Violation: You cannot use <HistoryLocation> without a DOM
    at invariant (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:2617:16)
    at createRouter (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:32660:6)
    at Object.runRouter [as run] (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:33424:17)
    at /Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:535:9
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:539:27)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:543:31)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:468:30)
    at /Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:493:37
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/react-hot-loader/index.js!/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/jorgef/dev/cervojo/node_modules/babel-loader/index.js!/Users/jorgef/dev/cervojo/scripts/index.jsx:496:10)
    at Module._compile (module.js:460:26)

ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!(webpack)-dev-server/client?http://localhost:3000
Module build failed: ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:4780:18)
    at Object.module.exports.module.exports.Object.keys.arr (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:5357:31)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:468:30)
    at fn (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:40:20)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:4601:15)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:468:30)
    at fn (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:40:20)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:4350:18)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:468:30)
    at fn (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack-dev-server/client/index.js?http://localhost:3000:40:20)

ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!(webpack)/hot/only-dev-server.js
Module build failed: ReferenceError: window is not defined
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack/hot/only-dev-server.js:553:26)
    at __webpack_require__ (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack/hot/only-dev-server.js:468:30)
    at /Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack/hot/only-dev-server.js:493:37
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/jorgef/dev/cervojo/node_modules/webpack/hot/only-dev-server.js:496:10)
    at Module._compile (module.js:460:26)
    at Object.loaderContext.exec (/Users/jorgef/dev/cervojo/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:86:7)
    at Object.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/extract-text-webpack-plugin/loader.js:93:22)
    at Tapable.<anonymous> (/Users/jorgef/dev/cervojo/node_modules/webpack/lib/Compiler.js:212:10)
    at /Users/jorgef/dev/cervojo/node_modules/webpack/lib/Compiler.js:400:12
    at Tapable.next (/Users/jorgef/dev/cervojo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:11)
Child extract-text-webpack-plugin:
        + 135 hidden modules
Child extract-text-webpack-plugin:
        + 490 hidden modules
Child extract-text-webpack-plugin:
        + 99 hidden modules
Child extract-text-webpack-plugin:
        + 46 hidden modules
```

**Comment by SanderSpies** [comment]
Yes, that's correct - perhaps the error could be a bit better though. 

What's happening is that your code is being run through node to extract all the CSS, so you can also use JS functions for your styling. However, the DOM is not available during that time - so any code linking to document or window will cause an error. 

The way to solve this is:
```
if (typeof window !== 'undefined) {
   // dom specific code
}
```

**Comment by jorda0mega** [comment]
I see, thanks for the clarification. It seems though that this would also be the case for external libraries included that reference the DOM (e.g. bootstrap). Is there any way to get around this without modifying the libraries themselves?

**Comment by SanderSpies** [comment]
Perhaps set the necessary objects + functions to pass? JSDom might work too, but seems a bit heavy though.

**Comment by tlightsky** [comment]
so,i should put this check to every render function in react?

**Comment by SanderSpies** [comment]
Not everywhere, see this example:
https://github.com/js-next/react-style/tree/master/examples/0.13/webpack
where only index.js contains the check but not the other modules.

**Comment by tlightsky** [comment]
I see,I add something like this:
```
if (typeof window !== 'undefined') {
  React.render(<Application />, document.getElementById('app'));
}
```
still get:
```
ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!./app.js
Module build failed: ReferenceError: window is not defined
```
even I comment whole render part,still get this error
the bad part is,i dont't know which line of my code cause this >_<

**Comment by SanderSpies** [comment]
@tlightsky - I'm afraid you have to do some digging through your code base to fix this - could be a dependency.

**Comment by tlightsky** [comment]
i see, thanks for your help anyway :)

**Comment by SanderSpies** [comment]
If there is any reason to reopen this let me know!

**Comment by danawoodman** [comment]
@tlightsky were you able to figure this out? I've done the suggested to no avail.

**Comment by tlightsky** [comment]
@danawoodman  no,I just use wachify and browserify | uglify now

**Comment by danawoodman** [comment]
@tlightsky not sure how that solves the problem of having a CSS file. @SanderSpies is there a reason that this plugin required `document` to be defined? I'm not clear how this works but I'd imagine some static analysis of the source could work. I'm not able for the life of me to get the plugin working with the above steps, including wrapping any of my `document` code with that conditional. Any other guidance you can offer?

**Comment by danawoodman** [comment]
Bump...

**Comment by danawoodman** [comment]
Perhaps there could be a way for this plugin to set/ignore missing variables like `window`/`document`/`navigator`?

**Comment by Norm-** [comment]
FWIW, this problem goes away when dev-server is not used.

**Comment by dmackerman** [comment]
@Norm- I'm not using dev-server, and I see this issue.

**Comment by Norm-** [comment]
@dmackerman 

I ran into this issue while using another lib. "window" or "navigator" not found happens a lot.

Admittedly, I don't exactly remember how I solved it in that particular instance. I remember I played around with these, though - https://webpack.github.io/docs/configuration.html#target

**Comment by web2style** [comment]
Thanks, @Norm-. Using `target: 'web',` helped to solve the problem.
