### ISSUE TITLE
Reference error: navigator is not defined when used with webpack-dev-server

### ISSUE THREAD

**Issue by goffreder** [js-next/react-style-webpack-plugin#19]
It looks like this plugin doesn't get along with `webpack-dev-server`. When I start the server, and with every recompile, it gives this error, which reflects in the devtools console:

```
./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!(webpack)-dev-server/client?http://0.0.0.0:8080
Module build failed: ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:9751:18)
    at Object.module.exports.module.exports.Object.keys.arr (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:10328:31)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:9572:15)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.module.exports.module.exports.fn (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:9309:18)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8919:16)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:9299:31)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8774:12)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8823:31)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8061:19)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8763:31)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8042:19)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:8034:20)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:7530:12)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.module.exports.module.exports (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:5556:16)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:5542:19)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:51:11)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:126:31)
    at __webpack_require__ (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:21:30)
    at /home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:43:18
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/react-style-webpack-plugin/lib/entry.js!/home/goffreder/dev/React/ple-react/node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080:46:10)
    at Module._compile (module.js:428:26)
    at Object.loaderContext.exec (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/extract-text-webpack-plugin/loader.js:93:22)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compiler.js:213:10)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compiler.js:401:12
    at Tapable.next (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Object.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Tapable.next (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compiler.js:398:9)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:569:13)
    at Tapable.applyPluginsAsync (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:564:10)
    at Tapable.applyPluginsAsync (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:559:9)
    at Tapable.applyPluginsAsync (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:555:8)
    at Tapable.applyPluginsAsync (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.seal (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:517:7)
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compiler.js:395:15)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Tapable.<anonymous> (/home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:438:10)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:410:12
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/lib/Compilation.js:325:10
    at done (/home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /home/goffreder/dev/React/ple-react/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

The output looks fine though, all the syles are applied as expected and the class names look correct, but it's very annoying as it clutters the console with the stacktrace.

This is my `webpack.config.js`:

```javascript
/*eslint-disable no-var */

var webpack = require('webpack');
var name = require('./package.json').name;
var description = require('./package.json').description;
var version = require('./package.json').version;

var ReactStylePlugin = require('react-style-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    devtool: process.env.NODE_ENV !== 'production' ? 'source-map' : null,

    entry: './app/App.js',

    output: {
        path: '__build__',
        publicPath: '__build__',
        filename: 'build.js'
    },

    module: {
        preLoaders: [{
            test: /\.jsx?$/,
            loader: 'eslint-loader'
        }],
        loaders: [{
            test: /\.jsx?$/,
            exclude: /node_modules[\/\\]/,
            loaders: [
                'babel-loader?optional[]=es7.decorators',
                ReactStylePlugin.loader()
            ]
        }, {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
        }, {
            test: /\.(eot|woff2|ttf|svg|woff)$/,
            loader: 'url-loader'
        }]
    },

    plugins: [
        new webpack.DefinePlugin({
            process: {
                env: {
                    NODE_ENV: '"' + process.env.NODE_ENV + '"'
                },
                appData: {
                    name: '"' + name + '"',
                    description: '"' + description + '"',
                    version: '"' + version + '"'
                }
            }
        }),
        new ReactStylePlugin('build.css'),
        new webpack.ProvidePlugin({
            React: 'react/addons',
            StyleSheet: 'react-style'
        })
    ],

    resolve: {
        extensions: ['', '.js', '.jsx']
    }
};

/*eslint-enable no-var */
```

As reported in https://github.com/js-next/react-style-webpack-plugin/issues/12, I added `if (typeof window !== 'undefined')` before my `render()` call, otherwise the console states that document is not defined instead.

**Comment by Agamennon** [comment]
I too have the same issue, perhaps a boilerplate project could help us into seeing our mistakes, anyone can point to a repo?
