### ISSUE TITLE
not working ...

### ISSUE THREAD

**Issue by ryanflorence** [js-next/react-style-webpack-plugin#9]
With this config:

```js
var webpack = require('webpack');
var ReactStylePlugin = require('react-style-webpack-plugin');

var PRODUCTION = process.env.NODE_ENV === 'production';

var plugins = function () {
  var all = [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'assets/vendor.js'),
    new ReactStylePlugin('assets/app.css')
  ];

  var production = [
    new webpack.optimize.UglifyJsPlugin({compress: {warnings: false}}),
    new webpack.optimize.DedupePlugin(),
    new webpack.DefinePlugin({
      "process.env": { NODE_ENV: JSON.stringify("production") }
    }),
    new webpack.NoErrorsPlugin()
  ];

  return PRODUCTION ? all.concat(production) : all;
};

module.exports = {

  entry: {
    app: "./app/main.js",
    vendor: [
      'react',
      'react-router',
      'client-firebase',
      'firebase-simple-login'
    ]
  },

  output: {
    filename: "assets/app.js",
    publicPath: "/"
  },

  devtool: PRODUCTION ? null : 'source-map',

  module: {
    loaders: [
      { test: /\.js$/, loader: 'jsx-loader?harmony&insertPragma=React.DOM' },
      { test: require.resolve('react'), loader: 'expose?React' },
      { test: /\.md$/, loader: "html!markdown" },
      { test: /\.js$/, loader: ReactStylePlugin.loader() }
    ]
  },

  plugins: plugins()

};
```

I get this error:

```
TypeError: Object #<Object> has no method 'replace'
    at Tapable.<anonymous> (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:45:26)
    at Tapable.applyPluginsAsyncWaterfall (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/node_modules/tapable/lib/Tapable.js:77:69)
    at Tapable.NormalModuleFactory.create (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:27:7)
    at Tapable.<anonymous> (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:198:11)
    at /Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:124:9)
    at Tapable.Compilation.addModuleDependencies (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:168:8)
    at Tapable.Compilation.processModuleDependencies (/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:156:7)
```

The line with an error (`webpack/lib/NormalModuleFactory.js:45`) is trying to do this:

```js
var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
```

Without the `ReactStylePlugin('assets/app.css')` in `plugins` a request is just a path to a module like this:

```
./utils/createRouter
```

But when the react style plugin is added, the request is the `entry` config (?)

```js
{ app: 
   [ '/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/client/index.js?http://localhost:2992',
     './app/main.js' ],
  vendor: 
   [ '/Users/ryanf/Code/playground/life-track/node_modules/webpack-dev-server/client/index.js?http://localhost:2992',
     'react',
     'react-router',
     'client-firebase',
     'firebase-simple-login' ] }
```

This is all I know.

**Comment by SanderSpies** [comment]
From what I can see here, we're not handling the entry propery of webpack config properly. If you use only a string, eg.  entry:  `"./app/main.js"` it will probably work. I don't have the complete setup locally so can't fully confirm if it will solve everything.

Of course, this should just work - so I will fix this.

**Comment by SanderSpies** [comment]
Small update: currently fighting with WebPack to get this working. It might take a while...

**Comment by SanderSpies** [comment]
Could you please try again with the #multiple-entries branch? 

There is also an example now that uses React Router and the CommonChunksPlugin: https://github.com/js-next/react-style/tree/inline-styles/examples/react-router

**Comment by SanderSpies** [comment]
We did some changes for multiple-entries support so this should work now.

**Comment by SrSandeepKumar** [comment]
Did you find a workaround ? facing the same error,

```/node_modules/webpack/lib/NormalModuleFactory.js:73
var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");```

`TypeError: request.replace is not a function`

Entry: 
{ main: './src/app/pages/app.js',
  headerFooter:
   [ './src/app/components/Header/client.js',
     './src/app/components/Footer/client.js' ] }
